apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: vote
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  replicas: 1

  template:
    metadata:
      name: postgres-pod
      namespace: vote
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432 # Deafult postgres port
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
