apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deploy
  namespace: vote
  labels:
    name: redis-deploy
    app:  demo-voting-app
spec:
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voting-app
  replicas: 1
  
  template:
    metadata:
      name: redis-pod
      namespace: vote
      labels:
        name: redis-pod
        app: demo-voting-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort:  6379
   