apiVersion: apps/v1
kind: Deployment
metadata:
  name:  worker-app-deploy
  namespace: vote
  labels:
    name: worker-app-deploy
    app:  demo-voting-app
spec:
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  replicas: 1
  
  template:
    metadata:
      name: worker-app-pod
      namespace: vote
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_worker:v1
   