apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo-localdocker-deployment
  namespace: test
  labels:
    app: acrdemo-localdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo-localdocker
  template:
    metadata:
      labels:
        app: acrdemo-localdocker
    spec:
      containers:
        - name: acrdemo-localdocker
          image: containerregistrydbaas.azurecr.io/app1/kube-nginx-acr:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true

          env:
          - name: ExampleSecret
            valueFrom:
              secretKeyRef:
                name: test-secrets
                key: secret-1
                
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-system-msi"
