# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: test
spec:
  provider: azure
  secretObjects:     

  - secretName: test-secrets
    type: Opaque
    labels:
      environment: "test"
    data:
    - objectName: ExampleSecret                   
      key: secret-1

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: ""      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: key-vault-dbaas
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret
          objectVersion: ""         
    tenantId: 93f33571-550f-43cf-b09f-cd331338d086          # The tenant ID of the key vault