apiVersion: v1
kind: Service
metadata:
  name: acrdemo-localdocker-service
  namespace: test
  labels:
    app: acrdemo-localdocker
spec:
  type: LoadBalancer
  selector:
    app: acrdemo-localdocker
  ports:
    - port: 80
      targetPort: 80